[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
# family = "JetBrainsMono Nerd Font Mono"
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
# family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
# family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "JetBrainsMono Nerd Font Mono"
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[general]
 import = [
 "~/.config/alacritty/gotham.toml"
]

[debug]
# Set the debug log level to help identify the issue
log_level = "debug"

# Optionally enable persistent logging for detailed logs
persistent_logging = true

[window]
startup_mode = "Windowed"   # Options: "Windowed", "Maximized", "Fullscreen"
opacity = 0.85              # 1.0 = opaque, 0.0 = fully transparent
decorations = "buttonless"

[window.padding]
x = 70
y = 70
